server:
  port: 8765

spring:
  application:
    name: eureka-client

eureka:
  #心跳设置，告诉服务器该实例仍在使用
  instance:
    lease-renewal-interval-in-seconds: 5
    #告诉服务器如果10秒内未发送任何续约请求，则关闭该客户端
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      company-name: in
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/,http://127.0.0.1:8763/eureka/

logging:
  level:
    com.netflix: INFO
