server:
  port: 9511

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/,http://127.0.0.1:8763/eureka/

spring:
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true