server:
  port: 8761
spring:
  profiles: eureka1

eureka:
  instance:
    hostname: eureka1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
  server:
    # 关闭自我保护
    enable-self-preservation: false
    # 清理服务器
    eviction-interval-timer-in-ms: 5000

# 日志输出
logging:
  file: log-eureka1/logger.log
  level:
    org.springframework.web: INFO

---

server:
  port: 8762
spring:
  profiles: eureka2
eureka:
  instance:
    hostname: eureka2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka3:8763/eureka/
  server:
    # 关闭自我保护
    enable-self-preservation: false
    # 清理服务器
    eviction-interval-timer-in-ms: 5000

# 日志输出
logging:
  file: log-eureka2/logger.log
  level:
    org.springframework.web: INFO
---

server:
  port: 8763
spring:
  profiles: eureka3
eureka:
  instance:
    hostname: eureka3
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
  server:
    # 关闭自我保护
    enable-self-preservation: false
    # 清理服务器
    eviction-interval-timer-in-ms: 5000

# 日志输出
logging:
  file: log-eureka3/logger.log
  level:
    org.springframework.web: INFO