spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/native
        git:
          uri: https://github.com/lijx0924/SpringClud.git
          search-paths: config-repo
          username: lijx0924@aliyun.com
          password: ljx123456789
server:
  port: 8888
