server:
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/native
        git:
          uri: https://github.com/lijx0924/SpringClud.git
          search-paths: config-repo
          username: lijx0924@aliyun.com
          password: ljx123456789
      label: master
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/,http://127.0.0.1:8763/eureka/


#spring:
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/native
#  profiles:
#     active: native
#  application:
#    name: config-server