server:
  port: 8766
spring:
  application:
    name: eureka-invocation
eureka:
  instance:
    # 心跳设置，告诉服务器该实例仍在使用
    lease-renewal-interval-in-seconds: 5
    # 告诉服务器如果10秒内未发送任何续约请求，则关闭该客户端
    lease-expiration-duration-in-seconds: 10

  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/,http://127.0.0.1:8763/eureka/
    # 抓取服务列表
    registry-fetch-interval-seconds: 30
# 默认负载均衡器规则
#default:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.boce.controller.MyRule

logging:
  level:
    com.netflix: DEBUG